### ISSUE TITLE
Update remaining DPC++ examples to eliminate deprecation warnings

### ISSUE THREAD

**Issue by klaeufer** [LoyolaChicagoBooks/unoapi#19]

**Comment by gkthiruvathukal** [comment]
@klaeufer Still relevant? Most of these warnings seem harmless. And they're relatively minor!

**Comment by klaeufer** [comment]
Fixed in https://github.com/LoyolaChicagoCode/unoapi-dpcpp-examples/commit/ff96335bd35a63d24e1b9e62e01b68de61be829a
