### ISSUE TITLE
Be careful with SVG

### ISSUE THREAD

**Issue by gkthiruvathukal** [LoyolaChicagoBooks/unoapi#31]
@klaeufer It is weird. Although there were no conflicts, apparently the build does not work with SVG. We need to investigate whether our Action workflow is reliably checking for build problems on HTML & PDF.  

In the interim, we must ensure that ``make html`` and ``make latexpdf`` both succeed before any commit.

I may have to comment out your SVG figures for now.

**Comment by klaeufer** [comment]
fixed in adae2fefc88e5910f3cb7ad6173ca8dc7e09c819

**Comment by klaeufer** [comment]
I reviewed some of the failed LaTeX builds, and they failed with an error message referencing the svg images.
